config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  
  # custom route - http verb url endpoint
  get '/about', to: 'static_pages#about'

  resources :pages
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    # returns an array of pages
    @pages = Page.all 
    # renders index.html.erb
  end

  def show
    #returns a single page with a single id
    @page = Page.find(params[:id]))
  end

  def new
    @page = Page.new 
    # creates database only in memory 
  end

  def create
    @page = Page.new(pages_params)
    if @page.save
      redirect_to pages_path
    else
      render :new
    end
  end

  def edit
  end

  private
  def pages_params
    params.require(:page).permit(:title, :author, :body)
  end

  # can also do create, edit, update and destroy
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'Pages', pages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogSum20</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% = render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/edit.html.erb
<h1>Pages#edit</h1>
<p>Find me in app/views/pages/edit.html.erb</p>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

<!-- erb embedded; echoing tags -->
<!-- # <% non-echoing tag ... for logic%>
# <%= echoing tag ... for when you want to display on to the page%> -->

<% @pages.each do |page| %>
  <%= page %>
  <%= link_to 'Show Page', page_path(page) %>

<% end %>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New Page </h1>

<%= form_for @page do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>

<%= f.label :author %>
<%= f.text_field :author %>

<%= f.label :body %>
<%= f.text_area :body %>

<%= f.submit %>
<% end %>

app/views/pages/show.html.erb
<%= @page.title %>
<%= @page.author %>
<%= @page.body %>
<!-- show all details of certain record;
   keeps broad wo works for every page-->
<%= link_to 'back', pages_path %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<h1>Home page</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>